AutoScout24/toguru-scala-client

build.sbt
Relying on ivy's 'latest-version' conflict resolution mechanism.
Given the current common practice in sbt, there is no chance of using proper version constraints.
By using a fixed version, we can let the users of this lib choose their version of play as long as it is greater than 2.5.4.
The drawback of this solution is that ivy's resolution mechanism will happily use a play version 2.6.x or even 3.x.
=> using fixed play version

build.sbt, src/main/scala/toguru/api/Activations.scala, src/main/scala/toguru/api/ToguruClient.scala, src/main/scala/toguru/impl/RemoteActivationsProvider.scala, src/main/scala/toguru/impl/ServerConnectivityMetrics.scala, src/main/scala/toguru/test/TestActivations.scala, src/test/scala/toguru/api/ToguruClientSpec.scala, src/test/scala/toguru/test/TestActivationsSpec.scala
- metrics about connectivity health and failures are now exposed via JMX
- connectivity health is computed with https://scholar.google.com/scholar?q=The+Phi+Accrual+failure+detector
as provided by https://github.com/komamitsu/phi-accural-failure-detector
- adding missing shutdown hooks and deregister/close calls
- adding test for ToguruClient
=> Adding metrics and health

src/main/scala/toguru/impl/Conditions.scala, src/test/scala/toguru/api/TogglingSpec.scala, src/test/scala/toguru/impl/ConditionsSpec.scala
Currently, the behaviour of a range condition is random picking a uuid when the client does not provide one. For a more stable behaviour, we propose to fallback to disabling the toggle in this case.
The consequence of this is that clients without uuids will not see the feature enabled unless it is forced on or uses an always on condition. Currently, rolling out a feature for clients without uuid will require additional code changes to be performed (i.e. changing the toggle default to always on). In the future, it should be possible to switch the toggle unconditionally on from the backend server, and make rolling out features to all clients simpler again.
=> Falling back to disabled toggle when client uuid is missing

.travis.yml, project/plugins.sbt, src/main/scala/toguru/api/Toggling.scala, src/main/scala/toguru/impl/ToggleStates.scala, src/test/scala/toguru/impl/ToggleStateSpec.scala
This is a PR which changes the `ToggleStateActivations.togglesFor` method:
- to accept multiple services in `services` tag (split by `,`) 
- and a new `service` tag with a single service (since many toggles are already configured this way).
- It is intended to be backward-compatible
- It removes the deprecation for `toggleStringForService` since this has its use cases (for example we can use it instead of [this](https://github.com/Scout24/classified-detail/blob/9cb79da612fcba291247f36112e6c287417fb3a0/app/classifieddetail/toguru/Toggles.scala#L99) )
=> Fix/extend ToggleStateActivations.togglesFor method and add related tests

.travis.yml, build.sbt, project/build.properties, project/plugins.sbt
Benefits:
- Proper version bumps (e.g. currently it will be `2.0.1-xxx` because the last tag is `2.0.0`)
- SemVer checks happen automatically when running tests
I disabled publishing for every commit on master because mixing released and "snapshot" artifacts is not nice. It also used to break the "latest version" badge in the readme.
=> Use sbt-git-versioning instead of sbt-git

build.sbt, core/src/test/scala/toguru/api/ActivationsSpec.scala, core/src/test/scala/toguru/api/ConditionSpec.scala, core/src/test/scala/toguru/api/ToggleSpec.scala, core/src/test/scala/toguru/api/TogglingSpec.scala, core/src/test/scala/toguru/api/ToguruClientSpec.scala, core/src/test/scala/toguru/impl/ConditionsSpec.scala, core/src/test/scala/toguru/impl/RemoteActivationsProviderSpec.scala, core/src/test/scala/toguru/impl/ToggleStateSpec.scala, core/src/test/scala/toguru/impl/TogglesStringSpec.scala, core/src/test/scala/toguru/impl/UuidDistributionConditionSpec.scala, core/src/test/scala/toguru/play/PlaySupportSpec.scala, core/src/test/scala/toguru/test/TestActivationsSpec.scala
* Remove two unused dependencies (`scalactic` and `commons-io`)
* Update patch versions of scala and compile dependencies
* Update test dependencies to the latest versions
I haven't updated `http4s` as it requires code changes, and I'm thinking of replacing the tests that start a real HTTP server with something more lightweight like `sttp` stubs.
=> Update and clean up dependencies

build.sbt, core/src/main/scala/toguru/impl/RemoteActivationsProvider.scala, core/src/test/scala/toguru/impl/RemoteActivationsProviderSpec.scala
With `sttp` we don't need to start a real HTTP server in tests, which is both simpler and faster. The default backend is `HttpURLConnectionBackend` (same as before with `scalaj-http`).
=> Use sttp instead of scalaj-http

build.sbt, core/src/main/scala/toguru/impl/RemoteActivationsProvider.scala
We use logging very little in the code, so to avoid additional dependencies we can use slf4j api directly.
=> Use SLF4J directly instead of scala-logging

build.sbt, core/src/main/scala/toguru/impl/RemoteActivationsProvider.scala, core/src/test/scala/toguru/impl/RemoteActivationsProviderSpec.scala
`com.hootsuite:scala-circuit-breaker` does not look maintained and also has some problems like depending on `logback` instead of `slf4j`.
`net.jodah:failsafe` is not scala-first, but is zero-dependency and supported.
=> Use failsafe as a circuit-breaker implementation

build.sbt
Going forward we will need to cross-build for Scala 2.13 and probably for different Play Framework versions. Maintaining compatibility with Scala 2.11 increases the effort.
I propose the declare the current `2.0.0` as the last version supporting 2.11.
=> Drop Scala 2.11 compatibility

build.sbt, core/src/main/scala/toguru/impl/RemoteActivationsProvider.scala, core/src/main/scala/toguru/impl/ToggleStates.scala, core/src/test/scala/toguru/impl/RemoteActivationsProviderSpec.scala
Using `play-json` as a JSON library makes it challenging to cross-build for different Play versions, especially if we want to have a "core" version of the scala client that doesn't depend on Play at all.
As a side-effect of this change, I dropped support for v1 and v2 response formats. Toguru uses v3 since 2017, if someone needs to work with the older toguru server, they will have to use toguru-scala-client 2.x.
=> Use circe instead of play-json

play/src/main/scala/toguru/play/package.scala
We don't need to depend on the full `Request`. Using `RequestHeader` makes it possible to use the client in Play filters.
Supersedes #30.
=> Depend on request header when possible

.travis.yml
To make it easier for people to test work-in-progress versions of the toguru-scala-client, let's start publishing snapshot versions again.
=> Publish snapshots to BinTray

build.sbt
BinTray does not allow SNAPSHOT versions
=> Drop SNAPSHOT suffix from the version string

build.sbt
`moduleName` was enough to publish with the right name, but the `SemVerPlugin` uses `name` setting.
=> Use name instead of moduleName

build.sbt
We have the `nop` logging implementation in tests and don't need `logback` as a second one.
=> Exclude logback from test dependencies

core/src/main/scala/toguru/impl/Conditions.scala, core/src/main/scala/toguru/impl/RemoteActivationsProvider.scala, core/src/main/scala/toguru/impl/ToggleStates.scala, core/src/main/scala/toguru/test/TestActivations.scala
To make it easier to maintain binary compatibility let's try to hide library internals.
=> Mark everything private as private

README.md
I guess the URL of the toguru panel used by AutoScout24 is not a big secret, but anyway it makes no sense to have it referenced in the README of a public repository.
=> Remove a reference to AutoScout24's toguru panel

core/src/main/scala/toguru/api/Activations.scala, core/src/main/scala/toguru/impl/RemoteActivationsProvider.scala, core/src/main/scala/toguru/test/TestActivations.scala, core/src/test/scala/toguru/api/ToguruClientSpec.scala, core/src/test/scala/toguru/impl/RemoteActivationsProviderSpec.scala
`Activations.fromEndpoint(...)` used to return an `Activations.Provider` that polls the server in the background, but there was no way to stop the polling without casting it to `RemoteActivationsProvider`.
=> Make activations provider closeable

.travis.yml
This was temporarily enabled because people wanted to have artifacts built for other scala and play versions, but it makes the version badge broken. After 3.0.0 release we shouldn't publish snapshots anymore, at least not to the same repository as releases.
If someone still needs snapshots, we should either create a second repository on BinTray, or maybe consider using GitHub Packages for this purpose.
=> Do not publish snapshots to BinTray
